# Compiler
CXX = clang++

# Targets
kahnsAlgo:
	$(CXX) kahnsAlgo.cpp -o kahnsAlgo && ./kahnsAlgo && rm kahnsAlgo

topologicalOrdering_DFS:
	$(CXX) topologicalOrdering_DFS.cpp -o topoDFS && ./topoDFS && rm topoDFS
