#Compiler
CXX = clang++

connectedGraphDFS:
	$(CXX) connectedGraphDFS.cpp -o connectedGraphDFS && ./connectedGraphDFS && rm connectedGraphDFS

reachabilityBFS:	
	$(CXX) reachabilityBFS.cpp -o reachabilityBFS && ./reachabilityBFS && rm reachabilityBFS